version: '3.8'
services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Docker/Dockerfile.dev
    container_name: soundcloud_backend_dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.dev