services:
  db:
    image: postgres:alpine
    container_name: harmonica-db-dev
    environment:
      POSTGRES_DB: SoundCloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SoundCloud"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: harmonica-redis-dev
    ports:
      - "6379:6379"

  backend:
    container_name: harmonica-backend-dev
    build:
      context: .
      dockerfile: Docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: harmonica-frontend-dev:latest
    build:
      context: ../Frontend
      dockerfile: Docker/Dockerfile.dev
    container_name: harmonica-frontend-dev
    volumes:
      - ../Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend