FROM node:20-alpine

WORKDIR /app

COPY package*.json ./


RUN npm install --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000 --legacy-peer-deps

COPY . .

EXPOSE 3000


CMD npm run migration:run && npm run dev