name: Deploy to AWS

on:
  push:
    branches: [main, staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
            echo "ENV_FILE=.env.prod" >> $GITHUB_ENV
            echo "PROJECT=prod" >> $GITHUB_ENV
          else
            echo "TAG=staging" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.staging.yml" >> $GITHUB_ENV
            echo "ENV_FILE=.env.staging" >> $GITHUB_ENV
            echo "PROJECT=staging" >> $GITHUB_ENV
          fi

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/harmonica-backend:${{ env.TAG }}

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app-new
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/harmonica-backend:${{ env.TAG }}
            docker compose -p ${{ env.PROJECT }} \
            -f ${{ env.COMPOSE_FILE }} \
            --env-file ${{ env.ENV_FILE }} \
            up -d --no-deps --force-recreate --pull always backend
            docker image prune -f
